### ISSUE TITLE
how to output the json even the value is null?

### ISSUE THREAD

**Issue by teddychan** [Rush/node-screener#1]
I have this code:

```
screen(result, {
name: true
title: true
}
```

but how to output the json like this?

```
{
name: "John",
title: "null"
}
```

as now i only get:

```
{
name: "John"
}

```

**Comment by Rush** [comment]
Sorry for late reply. Please check latest revision. I have added a test for your case.

**Comment by teddychan** [comment]
Thanks Rush, no need to say sorry.
We appreciate for your nice feedback and code update~~

**Comment by teddychan** [comment]
confirmed it is working now. if title is `null`, output will be:

```
title: "null"
```

Just one more thing, do u think that it is possible to add one more filter.
if the path is not exist, say `last_name` in the document, and also put as `null`

The reason is that, we don't have default value in our mongoDB for that path.
Normally if we you save a document and if the path is NOT there, it won't save anything.

But we want to unified the API output, so that all the client don't need to check if `typeof last_name === 'undefined'`, we simply give them null.

Any comments are welcome, or we will set the default null in our mongoose.

**Comment by Rush** [comment]
It's already possible, it's just kind of undocumented yet. Use `screen.api(object, spec)` or `screen(object, spec, {fill: true})`. If you want to do on field basis you would have to use your own screen, like this:

```
function nullUndefined(spec) {
   return function(object) {
       var field = screen(object, spec);      // you can replace this with screen.api and return immediately, I made it longer just for example if one needs custom working screen
       if(typeof field !== 'undefined')
          return field;
       return null;
    };
}
screen(yourObject, {last_name: nullUndefined(true)});
```

Such custom screen as a function could be registered using `screen.define`.

**Comment by Rush** [comment]
One could also make a default'ing screen that would work in the following manner: `var spec = { toDate: defaultScreen('date', new Date())};` This would whitelist an object if the toDate field has proper type (`date` is not a default screen btw.) or create a current date value. Note that a custom screen can actually parse the object's field and return some other value so it is quite flexible in nature.

I might add this behaviour as `screen.default` in the future, I have not decided yet. If you would have any ideas about improving the API please do not hesitate to make your case.
